#!/bin/bash -x
export IFS=$'\n'

CMDNAME=`basename $0`

## https://qiita.com/hit/items/e95298f689a1ee70ae4a                                                                                                                                                               
_pcnt=`pgrep -fo ${CMDNAME} | wc -l`               
if [ ${_pcnt} -gt 1 ]; then                        
	echo "This script has been running now. proc : ${_pcnt}"
	exit 1                                           
fi

##
if [ $# -ne 1 ]; then
	echo "Usage : ${CMDNAME} [directry]"
	exit 1
fi

TARGET_DIR=$1

##
EXTLIST=`cat /etc/mime.types | grep -v "#" | grep video | tr "\t" " " | tr -s " " | cut -d " " -f 2 | grep -v "/" | sort | uniq`
EXTLIST+=(
"mov"
"avi.mp4"
"wmv.mp4"
"flv.mp4"
"mpeg"
"mpg"
"flv"
"rmvb"
"wmv"
"m4a"
"avi"
"AVI"
"MPG"
"MPEG"
"ts"
"TS"
"webm"
)
EXTLIST+=($(echo "${EXTLIST[*]^^}" ))
EXTLIST=($(echo "${EXTLIST[*]}" | sort | uniq))

##
for EXT in ${EXTLIST[@]}
do
	for FILENAME in `find "${TARGET_DIR}" -name "*.${EXT}" | sort`
	do	       
		stream=`ffprobe -v error -select_streams v:0 -show_entries stream=width,height -i "${FILENAME}"`
		width=`echo $stream | cut -d " " -f 2 | cut -d "=" -f 2`
		height=`echo $stream | cut -d " " -f 3 | cut -d "=" -f 2`
		if [ $height -gt 1080 ] ; then
			echo 'over 2k'
			ffmpeg -i -y ${FILENAME} -vf scale=-1:1080 "2k_"${file} || continue
		       	rm -f ${FILENAME}
		fi
	done
done
