#!/bin/bash
export IFS=$'\n'

CMDNAME=`basename $0`

## https://qiita.com/hit/items/e95298f689a1ee70ae4a                                                                                                                                                               
_pcnt=`pgrep -fo ${CMDNAME} | wc -l`               
if [ ${_pcnt} -gt 1 ]; then                        
	echo "This script has been running now. proc : ${_pcnt}"
	exit 1                                           
fi

##
if [ $# -ne 1 ] && [ $# -ne 2 ] ; then
	echo "Usage : ${CMDNAME} [directry] [virtical resolution: ex. 720 / 1080 / 2160 / 4320]"
	exit 1
fi

TARGET_DIR=$1
VIRTICAL_RESOLUTION=1080
if [ $# -eq 2 ] ; then
	VIRTICAL_RESOLUTION=$2	
fi

##
EXTLIST=`cat /etc/mime.types | grep -v "#" | grep video | tr "\t" " " | tr -s " " | cut -d " " -f 2 | grep -v "/" | sort | uniq`
EXTLIST+=(
"mov"
"avi.mp4"
"wmv.mp4"
"flv.mp4"
"mpeg"
"mpg"
"flv"
"rmvb"
"wmv"
"m4a"
"avi"
"AVI"
"MPG"
"MPEG"
"ts"
"TS"
"webm"
)
EXTLIST+=($(echo "${EXTLIST[*]^^}" ))
EXTLIST=($(echo "${EXTLIST[*]}" | sort | uniq))

##
for EXT in ${EXTLIST[@]}
do
	for FILENAME in `find "${TARGET_DIR}" -name "*.${EXT}" | sort`
	do	       
		stream=`ffprobe -v error -select_streams v:0 -show_entries stream=width,height -i "${FILENAME}"`
		width=`echo $stream | cut -d " " -f 2 | cut -d "=" -f 2`
		height=`echo $stream | cut -d " " -f 3 | cut -d "=" -f 2`
		if [ $height -gt ${VIRTICAL_RESOLUTION} ] ; then
			ffmpeg -y -i ${FILENAME} -movflags +faststart -vf format=yuv420p scale=-1:${VIRTICAL_RESOLUTION} ${FILENAME%.${EXT}}_${VIRTICAL_RESOLUTION}p.mp4 || continue
		       	rm -f ${FILENAME}
		fi
	done
done
